compare_and_write
kshelekhin/scapy-iscsi pull request #11
Opened 2024-02-08 09:17 UTC by CaVaBang

Added CaW method and example

2024-02-08 14:14 UTC, heroin-moose commented on scapy_iscsi/iscsi.py
> +        XBitField("lb_num", 0x0, 8),
xfer_len, similar to READ16 and WRITE16

2024-02-08 14:42 UTC, heroin-moose requested changes
I don't think we need another example of an RW command.

2024-02-08 14:44 UTC, kshelekhin requested changes

2024-02-08 14:44 UTC, kshelekhin commented on scapy_iscsi/iscsi.py
> +        XBitField("lb_num", 0x0, 8),
xfer_len, similar to READ16 and WRITE16.

2024-02-09 07:53 UTC, kshelekhin approved these changes

2024-02-09 09:46 UTC, merged